### PR TITLE
bump requests version

### LINKED ISSUE #6: Please do not pin requests
This package has a specific pinning for the exact version of `requests==2.18.4` in the `install_requires` in the `setup.py`.
Please do not pin an exact version, but use a version constraint (e.g. `requests>=2.18.4`).
It is a very bad habit to pin exact versions in `setup.py` because if two packages do that they cannot be installed at the same time.

### PR DESCRIPTION
**Pull request by r-kells**

### CODE REVIEW

**Review by tizz98 — APPROVED** [review]
Thanks!

**Comment by r-kells** [comment]
@tizz98 Thanks for the quick reply! 

Going to upgrade my usage of this once you merge 👍

**Comment by r-kells** [comment]
@tizz98 Let me know If I can help with publishing this release!

**Comment by tizz98** [comment]
@r-kells I'll try to do it today, I'm currently with limited internet access

**Pull request merged**
